apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: home-delaleu-systems
  namespace: external-dns
spec:
  endpoints:
    - dnsName: home.delaleu.systems
      recordTTL: 300
      recordType: A
      targets:
        - 192.168.1.221
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: wildcard-home-delaleu-systems
  namespace: external-dns
spec:
  endpoints:
    - dnsName: "*.home.delaleu.systems"
      recordTTL: 300
      recordType: A
      targets:
        - 192.168.1.221
