apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: schedule-notifier
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: schedule-notifier
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: actual-password
      remoteRef:
        key: actualbudget-server-password
        version: CURRENT
        decodingStrategy: None
    # sync ID of your budget file (Settings > Show advanced settings > Sync ID)
    - secretKey: actual-sync-id
      remoteRef:
        key: actualbudget-sync-id
        version: CURRENT
        decodingStrategy: None
    # same admin password as set in NTFY server
    - secretKey: ntfy-password
      remoteRef:
        key: ntfy-admin-pass
        version: CURRENT
        decodingStrategy: None
