apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoyproxy
  # we set the namespace to flux-system to reuse the GitRepository created there
  # but set targetNamespace to envoy-gateway to install the resources there
  namespace: flux-system
spec:
  targetNamespace: envoy-gateway
  interval: 5m
  chart:
    spec:
      chart: ./gitops/core/envoy-gateway/charts
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: oci-lb-sg-id
      optional: false
      targetPath: ociNetworkSecurityGroup
      valuesKey: oci.lbsecuritygroup
