apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoyproxy
spec:
  interval: 5m
  type: oci
  url: oci://docker.io/envoyproxy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  interval: 2m
  timeout: 5m
  chart:
    spec:
      chart: gateway-helm
      version: "1.6.1"
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
      interval: 5m
  releaseName: envoy-gateway
