apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ntfy
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/ntfy
  prune: true
  dependsOn:
    - name: external-secrets
    - name: longhorn
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ntfy
      namespace: ntfy
