apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dex
spec:
  parentRefs:
    - name: envoy
      namespace: envoy-gateway
  hostnames:
    - "login.delaleu.systems"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: dex
          port: 5556
