apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-webhook
spec:
  parentRefs:
    - name: envoy
      namespace: envoy-gateway
  hostnames:
    - "flux-webhook.delaleusystems.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: webhook-receiver
          port: 80
---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: flux-web
# spec:
#   parentRefs:
#     - name: envoy
#       namespace: envoy-gateway
#   hostnames:
#     - "flux.delaleusystems.com"
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#       backendRefs:
#         - name: flux-operator
#           namespace: flux-system
#           port: 9080
