apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: s3-proxy
spec:
  parentRefs:
    - name: envoy
      namespace: envoy-gateway
  hostnames:
    - "s3.delaleu.systems"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: s3-proxy
          port: 80
