apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actualbudget
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/actualbudget/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets
    - name: longhorn
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: actualbudget
  #     namespace: actualbudget
