apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: community-charts
spec:
  interval: 5m
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: actualbudget
      version: '1.8.6'
      sourceRef:
        kind: HelmRepository
        name: community-charts
      interval: 5m
  releaseName: actualbudget
  values:
    image:
      repository: docker.io/actualbudget/actual-server
    persistence:
      enabled: true
    files:
      server: /data/server-files
      user: /data/user-files
    strategy:
      type: Recreate # recommended for single-instance deployments
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    # we don't have Ingress controller but actualbudget chart only mounts OpenID config when Ingress is configured
    # see https://github.com/community-charts/helm-charts/blob/cfc4efef4bef8d1ab9c3f669380f09368d2df04a/charts/actualbudget/templates/deployment.yaml#L75
    # and https://github.com/community-charts/helm-charts/blob/cfc4efef4bef8d1ab9c3f669380f09368d2df04a/charts/actualbudget/templates/secret.yaml#L18-L21
    ingress:
      enabled: true
      hosts:
        - host: budget.delaleusystems.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
       - secretName: actualbudget-tls
         hosts:
           - budget.delaleusystems.com
    login:
      allowedLoginMethods:
        - openid
        - password  # Required for @actual-app/api library access (schedule notifier)
      method: openid
      openid:
        enforce: false  # Allow password auth for API while keeping OIDC as default
        providerName: dex
        discoveryUrl: https://login.delaleusystems.com/dex/.well-known/openid-configuration
        authMethod: openid
        tokenExpiration: 3600
        existingSecret:
          name: dex-actualbudget-client
          clientIdKey: actualbudget.client-id
          clientSecretKey: actualbudget.client-secret
