apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: community-charts
spec:
  interval: 5m
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
spec:
  install:
    disableSchemaValidation: true
  upgrade:
    disableSchemaValidation: true
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: actualbudget
      version: '1.8.6'
      sourceRef:
        kind: HelmRepository
        name: community-charts
      interval: 5m
  releaseName: actualbudget
  values:
    image:
      repository: docker.io/actualbudget/actual-server
    persistence:
      enabled: true
    files:
      server: /data/server-files
      user: /data/user-files
    strategy:
      type: Recreate # recommended for single-instance deployments
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    login:
      method: "oauth2"
      openid:
        authMethod: oauth2
        enforce: true
        providerName: GitHub
        authorizationEndpoint: https://github.com/login/oauth/authorize
        tokenEndpoint: https://github.com/login/oauth/access_token
        userinfoEndpoint: https://api.github.com/user
        # discoveryUrl:
        tokenExpiration: 3600
        existingSecret:
          name: "actualbudget-github-app-oauth-secret"
          clientIdKey: "clientId"
          clientSecretKey: "clientSecret"
