apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gatewayapi
  namespace: flux-system
spec:
  interval: 1h
  ref:
    tag: v1.4.1
  url: https://github.com/kubernetes-sigs/gateway-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatewayapi-crds
  namespace: flux-system
spec:
  interval: 1h
  path: ./config/crd/standard
  prune: true
  sourceRef:
    kind: GitRepository
    name: gatewayapi
