apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bagisto
spec:
  parentRefs:
    - name: envoy
      namespace: envoy-gateway
  hostnames:
    - "store.delaleusystems.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: bagisto
          port: 80
